image: python:3.9

stages:
  - test
  - report

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  ALLURE_RESULTS: "allure-results"
  ALLURE_REPORT: "allure-report"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install pytest pytest-allure-adaptor allure-pytest

test:
  stage: test
  script:
    - pytest --alluredir=$ALLURE_RESULTS
  artifacts:
    paths:
      - $ALLURE_RESULTS
    when: always

report:
  stage: report
  dependencies:
    - test
  script:
    - allure generate $ALLURE_RESULTS -o $ALLURE_REPORT
    - mv $ALLURE_REPORT public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main

pages:
  stage: report
  dependencies:
    - report
  script:
    - mv public/ $CI_PROJECT_DIR/public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main
