image: python:3.10

stages:
  - test
  - report

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  ALLURE_RESULTS: "allure-results"
  ALLURE_REPORT: "allure-report"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest allure-pytest
  - curl -sLo allure-2.13.8.tgz https://github.com/allure-framework/allure2/releases/download/2.13.8/allure-2.13.8.tgz
  - tar -xzf allure-2.13.8.tgz
  - mv allure-2.13.8 /opt/allure
  - export PATH=$PATH:/opt/allure/bin

test:
  stage: test
  script:
    - pytest --alluredir=$ALLURE_RESULTS
  artifacts:
    paths:
      - $ALLURE_RESULTS
    when: always

report:
  stage: report
  dependencies:
    - test
  script:
    - /opt/allure/bin/allure generate $ALLURE_RESULTS -o $ALLURE_REPORT
    - mv $ALLURE_REPORT public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main

pages:
  stage: report
  dependencies:
    - report
  script:
    - mv public/ $CI_PROJECT_DIR/public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main
