image: python:3.10

stages:
  - test
  - report
  - deploy

variables:
  REPORTS_DIR: allure-report
  ALLURE_VERSION: 2.13.8

before_script:
  - apt-get update && apt-get install -y python3 python3-pip wget unzip
  - wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/$ALLURE_VERSION/allure-commandline-$ALLURE_VERSION.zip -O allure.zip
  - unzip allure.zip -d /opt/
  - export PATH=$PATH:/opt/allure-$ALLURE_VERSION/bin

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pytest --alluredir=${REPORTS_DIR}/results

report:
  stage: report
  script:
    - allure generate ${REPORTS_DIR}/results -o ${REPORTS_DIR}/report
  artifacts:
    paths:
      - ${REPORTS_DIR}/report

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r ${REPORTS_DIR}/report/* public
  artifacts:
    paths:
      - public
  only:
    - main
